name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      trigger_mode:
        description: "Select your trigger mode :"
        required: true
        type: choice
        options:
          - BE TAG SANITY
          - MOBILE REGRESSION
          - WEB REGRESSION
          - API REGRESSION
      qa_box:
        description: "Select your QA box :"
        default: 1
        required: true
        type: number

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_WORKSPACE: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected options
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Run tests: ${{ github.event.inputs.run_tests }}"
